version: '2'
services:
#  db:
#    image: mysql
#    expose: - "3306"
#    ports: - 3306:3306
#    environment: - MYSQL_DATABASE=YourDatabaseName - MYSQL_ROOT_PASSWORD=YourPassWord
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - 6061:80
#      links:
#      - db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
      ports: - "8000:8000"
      links: - db


